# Generated by Django 3.2 on 2021-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_link1', models.CharField(max_length=200)),
                ('pdf_link2', models.CharField(max_length=200)),
                ('pdf_link3', models.CharField(max_length=200)),
                ('pdf_link4', models.CharField(max_length=200)),
                ('pdf_link5', models.CharField(max_length=200)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('content4', models.TextField()),
                ('content5', models.TextField()),
            ],
        ),
    ]
